# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# from _typeshed import Self
from PyQt5 import QtCore, QtGui, QtWidgets
from tool import *
import requests

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(630, 362)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(190, 10, 271, 91))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 170, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(120, 100, 191, 41))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(120, 170, 191, 41))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(210, 260, 141, 51))
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(230, 330, 141, 17))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(350, 80, 271, 181))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../Downloads/Uchiha.Itachi.full.1065290-removebg-preview.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")

        #run
        self.pushButton.clicked.connect(self.run)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Tool"))
        self.label.setText(_translate("Dialog", "Crawl Image "))
        self.label_2.setText(_translate("Dialog", "Title:"))
        self.label_3.setText(_translate("Dialog", "Folder:"))
        self.pushButton.setText(_translate("Dialog", "Start Crawl "))

    def run(self):
        driver = webdriver.Chrome(executable_path="./driver/chromedriver")
        url = "https://www.google.com/search?q={}&site=webhp&tbm=isch".format(self.textEdit.toPlainText())
        driver.get(url)
        #keo den khi nao nhan vao nut them anh 
        self.scroll_page(driver)
        self.click_button(driver)
        #tim anh 
        img_urls = self.find_images(driver)
        # print(img_urls)
        #dong driver
        driver.close()
        self.download(self.textEdit_2.toPlainText(), img_urls)
        
    def click_button(self, driver):
        more_imgs_button_xpath = '/html/body/div[2]/c-wiz/div[3]/div[1]/div/div/div/div[1]/div[2]/div[2]/input'
        driver.find_element_by_xpath(more_imgs_button_xpath).click()  

    def scroll_page(self, driver):
        for i in range(7):
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
            sleep(3)

    def find_images(self, driver):
        html_source = driver.page_source
        soup = BeautifulSoup(html_source, 'html.parser')

        imgs_urls = []
        for img in soup.find_all('img'):
            try:
                if img['src'].startswith('http'):
                    imgs_urls.append(img['src'])
            except:
                pass 

        return imgs_urls

    def download(self, folder, img_urls):
        if (os.path.isdir(folder)):
            pass 
        else:
            os.mkdir(folder)
        for i in range(len(img_urls)):
            response = requests.get(img_urls[i])
            name = "image{}".format(i)
            file = open("./image/"+name+".png", "wb")
            file.write(response.content)
            file.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
